export type SwapServiceErrorCode =
	| 'UNSUPPORTED_CHAIN'
	| 'UNSUPPORTED_TOKEN'
	| 'INVALID_AMOUNT'
	| 'AMOUNT_TOO_LOW'
	| 'AMOUNT_TOO_HIGH'
	| 'ORDER_NOT_FOUND'
	| 'SESSION_NOT_FOUND'
	| 'SIGNING_SESSION_UNSUPPORTED'
	| 'SIGNING_SESSION_INCOMPLETE'
	| 'NO_SIGNATURES_REQUIRED'
	| 'INVALID_REQUEST'
	| 'INVALID_RESPONSE'
	| 'UNKNOWN_ERROR';
